Travis ci
femiwiki/docker-mediawiki pull request #249
Opened 2019-01-11 05:49 UTC by lens0021

issue: https://github.com/femiwiki/mediawiki/issues/242

2019-01-11 06:29 UTC, simnalamburt commented
이번 노동톤때에 리뷰할게요 죄송해요 시간이 안나네요

2019-01-11 06:29 UTC, lens0021 commented
앗 네 그럴려고 올린거였어요

2019-01-25 11:01 UTC, lens0021 commented
(참고)이 PR의 체크 실패는 install-extensions.php의 린트 때문에 일어난 것이나 master branch에는 해당 파일이 없으므로 무시해도 됩니다.

2019-02-01 17:37 UTC, simnalamburt requested changes
`.travis.yml` 안에있는 긴 셸스크립트들 읽기힘든데 주석좀 넣어주세요 특히 반복문 근처 코드들

2019-02-01 17:37 UTC, simnalamburt commented on composer.json
> +    "mediawiki/minus-x": "0.3.1"
이거 하지맙시다

2019-02-01 17:37 UTC, simnalamburt commented on .gitignore
> +.phpcs.xml
이거 gitignore에 넣지말고 PHP lint 할거면 `.phpcs.xml` 파일을 저장소에 커밋해버리는게 나을듯

2019-02-01 17:37 UTC, simnalamburt commented on .gitignore
> +/composer.lock
이것도 무시하지말고 커밋하는게 나을듯

2019-02-01 17:37 UTC, simnalamburt commented on .travis.yml
> +        - "docker exec $(docker container ls -qf name=mediawiki_fastcgi)
남의 라이브러리들까지 우리가 테스트할필요는 없을듯

2019-02-01 17:37 UTC, simnalamburt commented on .travis.yml
> +            composer install --prefer-source --quiet --no-interaction
아래와 같이 하면 docker exec 한번에 여러 줄 실행할 수 있어요

```
docker exec -it blabla bash -c 'echo hi && echo hi;'
```

외따옴표 안에 커맨드 길게 쓰는게 불편하면

```
xargs -0 docker exec -it blabla bash -c -- <<'EOF'
echo hi &&
echo hi
EOF
```

이렇게하시면 됨

2019-02-02 02:19 UTC, lens0021 commented on composer.json
> +    "mediawiki/minus-x": "0.3.1"
3-6인가로 표시되어 있는데 line 6만 얘기하신 거 같아서 minus-x만 뺐습니당

2019-02-02 09:32 UTC, simnalamburt requested changes

2019-02-02 09:32 UTC, simnalamburt commented on .travis.yml
> +        - php -l configs/secret.example.php
`secret.php.example`로 고쳐야함

2019-02-02 09:32 UTC, simnalamburt commented on .travis.yml
> +        - cp configs/secret.example.php configs/secret.php
`secret.php.example`로 고쳐야함

2019-02-02 09:32 UTC, simnalamburt commented on .gitignore
> +.phpcs.xml
.gitignore에서 생긴 변화들 .dockerignore에도 똑같이 반영해주세요

2019-02-02 11:32 UTC, simnalamburt approved these changes

2019-02-02 12:29 UTC, merged