RESTBase 장소 이동 및 카산드라 사용
femiwiki/docker-mediawiki pull request #257
Opened 2019-02-09 08:10 UTC by lens0021

- RESTBase가 데이터베이스 서버에서 미디어위키 서버로 옮겨갈 수 있도록 도커 컴포즈 파일 수정
- RESTBase 컨테이너를 위한 프록시를 캐디 설정에 추가
- RESTBase 관련 설정을 미디어위키에 추가

#### 관련 이슈

- https://github.com/femiwiki/femiwiki/issues/52

2019-02-12 12:28 UTC, simnalamburt reviewed
주석 달은거 좋네요

2019-02-12 12:28 UTC, simnalamburt commented on development.yml
> +    image: femiwiki/mediawiki:cassandra ## TODO 태그 제거하기
태그가 카산드라인건 별로인거같고, 저희 도커이미지에 버저닝을 이제 해야할때가 온것같네요.

`femiwiki/mediawiki:2019-02-12` 이렇게 날짜만 쓸까요 아니면

`femiwiki/mediawiki:2019-02-12T15:13` 이렇게 시간까지 쓸까요?

기존에는 `femiwiki/mediawiki:2019-02-12-r1` 이렇게 하루에 릴리즈 몇번했냐로 이야기했었는데 이건 좀 별로인거같은.. 회수로할거면 차라리 `femiwiki/mediawiki:build-1324` 이렇게 아예 쌩으로 빌드번호만 쓰는게 나을거같아요. 어떻게 생각하시나요

2019-02-12 12:28 UTC, simnalamburt commented on development.yml
> +    image: femiwiki/restbase:cassandra ## TODO 태그 제거하기
이 역시 버저닝 스키마 결정한 다음 고쳐야함

2019-02-12 12:43 UTC, lens0021 commented on development.yml
> +    image: femiwiki/mediawiki:cassandra ## TODO 태그 제거하기
이 cassandra 태그는 femiwiki/mediawiki 리포의 카산드라 사용을 새로운 feature로 보고 브랜치를 나누었기 때문에 도커 이미지에서도 이를 구분하기 위해 붙인 것으로 날짜나 빌드번호를 붙이는 것은 마스터 브랜치를 바탕으로 한 이미지들에서만 일직선 상에서만 이루어져야 할 것 같아 곤란해 보입니다. 아니면 마스터는 마스터대로 버저닝을 하고 이 부분은 `cassandra-1234`와 같이 태그를 붙이는 것을 말씀하시는 것인가요?

2019-02-12 12:57 UTC, simnalamburt commented on development.yml
> +    image: femiwiki/mediawiki:cassandra ## TODO 태그 제거하기
제가 원하는거

```
* femiwiki/mediawiki:build-10 (미래의 이미지)
| *
| *
| / 
* femiwiki/mediawiki:build-9 
* femiwiki/mediawiki:build-8
```

마스터에 머지 안한건 배포할일이 없을테니 이렇게될거같네요

2019-02-12 13:11 UTC, lens0021 commented on development.yml
> +    image: femiwiki/mediawiki:cassandra ## TODO 태그 제거하기
호엥 저는 숫자 붙이는 게 간단해서 좋을 거 같아요

2019-02-13 02:23 UTC, simnalamburt commented on development.yml
> +    image: femiwiki/mediawiki:cassandra ## TODO 태그 제거하기
- `femiwiki/mediawiki:build-123`
- `femiwiki/mediawiki:release-123`

둘중 하나 쓰면 될거같아요. 당분간은 `femiwiki/mediawiki:build-123` 쓰고, 나중에 CI/CD 자동화가 되면 `femiwiki/mediawiki:release-123` 로 옮길까 싶네요.

2019-02-13 06:21 UTC, lens0021 commented on development.yml
> +    image: femiwiki/mediawiki:cassandra ## TODO 태그 제거하기
도커 허브에서 태그 붙이었고 마스터에서 아래와 같이 수정했습니다

https://github.com/femiwiki/mediawiki/commit/c23f8311650d4fa3d3cac07525096151c1189555#diff-3254677a7917c6c01f55212f86c57fbfR10

이 PR에서 해당 부분은 아래와 같습니다. (태그를 바꾸려고 보니까 이 PR이 도커 이미지에 주는 영향이 없어서 그대로 0입니다)

https://github.com/femiwiki/mediawiki/blob/91ce11af8a0d846ce54231463a76fda18f2486c8/production.yml#L10-L11

2019-02-13 06:24 UTC, lens0021 commented on development.yml
> +    image: femiwiki/restbase:cassandra ## TODO 태그 제거하기
https://github.com/femiwiki/mediawiki/pull/257/files#diff-8857124ebdcf7d878ada27a8dd023ea4R21

위와 같이 수정하였습니다 :-)

2019-02-14 05:49 UTC, simnalamburt requested changes
아래와 같이 고쳐주세요

RESTBASE_DB_HOSTNAME → CASSANDRA_HOSTNAME
RESTBASE_DB_USERNAME → CASSANDRA_USERNAME
RESTBASE_DB_PASSWORD → CASSANDRA_PASSWORD

2019-02-14 05:55 UTC, lens0021 commented
>아래와 같이 고쳐주세요
>
>RESTBASE_DB_HOSTNAME → CASSANDRA_HOSTNAME
RESTBASE_DB_USERNAME → CASSANDRA_USERNAME
RESTBASE_DB_PASSWORD → CASSANDRA_PASSWORD

고쳤습니다~ https://github.com/femiwiki/mediawiki/commit/0b079d6ed4cff6fe22df1da7298aff43bc55b5c0

2019-02-14 06:05 UTC, merged