RESTBase 재도입
femiwiki/docker-mediawiki pull request #289
Opened 2019-07-25 13:02 UTC by lens0021

https://github.com/femiwiki/femiwiki/issues/86

TBD

2019-07-25 14:36 UTC, HanbitGaram reviewed
ENG:
The modified code is intuitive and neat.
Did this code work correctly in the development environment?

I had the Docker environment initialized in my macbook, I need to reinstall it to test it.

KOR:
팀에서 리뷰하듯이 편하게 해볼게요!
우와! 코드가 엄청 깔끔합니다! 저렇게 설정하면 다 알아서 해주다니 이거 완전 대박 아니에요??

* 이 코드가 개발환경에서 정상작동했나요?? https://페미위키닷컴/페미위키/ 로컬셋팅즈 파일 283번째 줄 경로를 저렇게 설정하신건 의도하신건가요?? 
* 완벽해요! 저도 코드 쓰는거 닮고 싶어요! 주석이 필요 없습니다!
* 용량이 없어서 도커를 지웠어요. 그래서 지금 테스트를 할 수 없습니당.. ㅠㅠㅠ

2019-07-25 14:57 UTC, lens0021 commented
@HanbitGaram 

> 이 코드가 개발환경에서 정상작동했나요??

wikitext와 HTML를 전환하는 간단한 테스트는 잘 작동했습니다~!

> https://페미위키닷컴/페미위키/ 로컬셋팅즈 파일 283번째 줄 경로를 저렇게 설정하신건 의도하신건가요??

283번째 줄은 다행히 프로덕션용이라 개발환경에는 영향이 없습니다 개발환경에서는 다음 내용이 적용됩니다:

https://github.com/femiwiki/mediawiki/blob/936e7b5c21a723961a87f01555743577aa713ba1/configs/LocalSettings.php#L638-L639

`DEBUG_MODE`는 secret.php에서 정의됩니다:

https://github.com/femiwiki/mediawiki/blob/936e7b5c21a723961a87f01555743577aa713ba1/configs/secret.php.example#L3-L4

그러나 어쨌든 `https://femiwiki.com/femiwiki.com`에 대한 요청은 Caddy의 다음 프록시에 따라서 `restbase:7231`로 보내집니다:

https://github.com/femiwiki/mediawiki/blob/936e7b5c21a723961a87f01555743577aa713ba1/caddy/Caddyfile#L13-L16

그 이유에 대한 설명은 주석의 [링크](https://www.mediawiki.org/wiki/RESTBase/Installation#Proxy_requests_to_RESTBase_from_your_webserver) 등을 참고하시면 될 것 같습니다, 감사합니다!

2019-07-25 15:22 UTC, simnalamburt requested changes
Blocked by https://github.com/femiwiki/docker-restbase/pull/4

2020-01-06 11:08 UTC, lens0021 commented
Closed by https://github.com/femiwiki/femiwiki/issues/149

2020-01-06 11:08 UTC, closed without merging