Make Caddy serve HTTPS
femiwiki/docker-mediawiki pull request #298
Opened 2019-10-30 22:32 UTC by lens0021

2019-10-30 22:37 UTC, lens0021 commented on caddy/Caddyfile
> +*.femiwiki.com:443
이렇게 했을 때 `https://test.femiwiki.com`는 잘 되던데, `https://femiwiki.com`도 더불어 그럴까요?

2019-10-31 02:44 UTC, simnalamburt commented on caddy/Caddyfile
> +*.femiwiki.com:443
아뇨안돼요 그리고 뒤에있는 `:443` 도 떼셔야할거같아요

아마 `femiwiki.com, *.femiwiki.com` 이런식으로 하면 될텐데 문서한번 봐보세요

2019-10-31 02:48 UTC, simnalamburt commented on caddy/Caddyfile
> +*.femiwiki.com:443
콤마 없이 `femiwiki.com *.femiwiki.com` 이렇게 하는거네요

그리고 `femiwiki.com:443` 하면 443포트만 리슨하는데 `femiwiki.com` 이렇게쓰면 80 443 둘다리슨하고 80으로 들어오는건 443으로 리다이렉투시키거든요 그래서 하라고 말씀드린거였어요

2019-10-31 03:02 UTC, simnalamburt requested changes
지금보니 압축이 빠져있네요 이거 넣읍시다 https://caddyserver.com/v1/docs/gzip

`gzip` 이라고 딱 한문장만 넣으면 돼요

```
    header / {
        # HSTS
        Strict-Transport-Security "max-age=15768000"
        # Enable XSS filtering for legacy browsers
        X-XSS-Protection "1; mode=block"
        # Block content sniffing, and enable Cross-Origin Read Blocking
        X-Content-Type-Options "nosniff"
        # Avoid clickjacking
        X-Frame-Options "DENY"
    }
```

이것도 넣읍시다 https://en.m.wikipedia.org/wiki/HTTP_Strict_Transport_Security

웹브라우저가 저 헤더를 한번이라도 읽으면, 그 다음부턴 사용자가 http://femiwiki.com 을 주소창에 쳐도, 암호화 안되고 MITM에 취약한 HTTP 리퀘를 아예 안보내고 자동으로 시작부터 HTTPS 요청을 보내게 해요

HSTS를 해도 웹브라우저를 설치한 이후 맨 처음 접속할때엔 http를 쓴다는 문제가 있는데 이건 https://hstspreload.org/ 이런데에 신청하면 웹브라우저에 HSTS정보가 내장되게 만들어서 페미위키를 들어온적이 없어도 자동으로 https만 쓰게 되는거에요

HSTS 하고나서 잘 굴러가는거 확인하면 그뒤엔 HSTS 프리로딩도 켜면 좋을거같아요

2019-10-31 03:06 UTC, lens0021 commented
TODO: travis가 실패해서 `*:80`는 남겨야할거같습니다

2019-10-31 03:20 UTC, simnalamburt commented
개발용 Caddyfile이랑 프로덕션용 Caddyfile을 따로 운영하는건 어떨까요. `caddy/Caddyfile.dev` `caddy/Caddyfile.prod` 이렇게 두개 만들어서, 개발용은 `*:80` 프로덕션용은 `femiwiki.com` 이렇게요

`*:80 femiwiki.com` 이렇게 쓰면 80포트로 접근했을때 443포트로 리다이렉션을 시키지 못할거고, travis가 인증서 발급 시도하다가 실패할거에요

2019-10-31 05:02 UTC, lens0021 commented
gzip, HSTS 헤더 추가하고 Caddyfile 나눴습니다

2019-10-31 05:21 UTC, simnalamburt requested changes
```
# Enable XSS filtering for legacy browsers
X-XSS-Protection "1; mode=block"
# Block content sniffing, and enable Cross-Origin Read Blocking
X-Content-Type-Options "nosniff"
# Avoid clickjacking
X-Frame-Options "DENY"
```

이건 개발용에서도 넣는게 맞을거같아요

2019-10-31 05:24 UTC, simnalamburt requested changes

2019-10-31 05:24 UTC, simnalamburt commented on caddy/Caddyfile.dev
> +  # HSTS
개발용에선 HSTS는 끄시고 밑에 세개만 넣어야해요

2019-10-31 05:28 UTC, simnalamburt approved these changes
LGTM, 머지하신뒤 적용시켜보시고 문제있으면 롤백해주세요

2019-10-31 06:56 UTC, merged