"Solve #179"
femiwiki/docker-mediawiki pull request #381
Opened 2020-03-15 12:24 UTC by love-adela

* 분 까지만 표시
* git sha를 6글자가 아니라 8글자 뜨게함

2020-03-15 13:01 UTC, lens0021 requested changes
PR이 이슈랑 연결되어 있지 않은데 오른쪽 Linked pull requests에서 수동 연결 해주시면 감사하겠습니다~

2020-03-15 13:01 UTC, lens0021 commented on .github/workflows/test-and-publish.yml
> +    - run: echo "::set-output name=tag::$(date +%Y-%m-%d-%H%M)$(echo ${{ github.sha }} | cut -c1-8)"
```suggestion
    - run: echo "::set-output name=tag::$(date +%Y-%m-%dT%H:%M)$(echo ${{ github.sha }} | cut -c1-8)"
```

2020-03-15 13:52 UTC, lens0021 approved these changes

2020-03-15 13:54 UTC, lens0021 commented
악 콜론 못쓰는구나 죄송해유 적당히 고쳐주세요

2020-03-15 22:36 UTC, simnalamburt commented
이거 왠지 콜론때문에 실패할거같은데 테스트 해보신거 맞나요?

2020년 3월 15일 (일) 22:01, Lens0021 <notifications@github.com>님이 작성:

> *@lens0021* requested changes on this pull request.
>
> PR이 이슈랑 연결되어 있지 않은데 오른쪽 Linked pull requests에서 수동 연결 해주시면 감사하겠습니다~
> ------------------------------
>
> In .github/workflows/test-and-publish.yml
> <https://github.com/femiwiki/docker-mediawiki/pull/381#discussion_r392671553>
> :
>
> > @@ -37,7 +37,7 @@ jobs:
>
>          printf 'const DEBUG_MODE = 'localhost';\nrequire_once "$IP/includes/DevelopmentSettings.php";\n' >> configs/LocalSettings.php;
>
>          sed -i'' -r 's/femiwiki\/mediawiki:.+/femiwiki\/mediawiki:docker-test/' development.yml
>
>
>
> -    - run: echo "::set-output name=tag::$(date +%Y%m%d%H%M%S)$(echo ${{ github.sha }} | cut -c1-6)"
>
> +    - run: echo "::set-output name=tag::$(date +%Y-%m-%d-%H%M)$(echo ${{ github.sha }} | cut -c1-8)"
>
>
> ⬇️ Suggested change
>
> -    - run: echo "::set-output name=tag::$(date +%Y-%m-%d-%H%M)$(echo ${{ github.sha }} | cut -c1-8)"
>
> +    - run: echo "::set-output name=tag::$(date +%Y-%m-%dT%H:%M)$(echo ${{ github.sha }} | cut -c1-8)"
>
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/femiwiki/docker-mediawiki/pull/381#pullrequestreview-374797189>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABB235OR73NT7R2YPTQZZVTRHTGR3ANCNFSM4LK5AZRQ>
> .
>

2020-03-24 08:03 UTC, lens0021 commented
콜론 대신에 그러면 하이픈으로 할까요??

2020-03-24 08:04 UTC, simnalamburt commented
좋아여

2020년 3월 24일 (화) 17:04, Lens0021 <notifications@github.com>님이 작성:

> 콜론 대신에 그러면 하이픈으로 할까요??
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/femiwiki/docker-mediawiki/pull/381#issuecomment-603088195>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABB235JZ6OG24TOLM5YLK3TRJBSPJANCNFSM4LK5AZRQ>
> .
>

2020-03-24 08:17 UTC, merged